[2022-12-07T16:44:00.853+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-07T16:07:12.235594+00:00 [queued]>
[2022-12-07T16:44:00.860+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-07T16:07:12.235594+00:00 [queued]>
[2022-12-07T16:44:00.861+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-07T16:44:00.862+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 5 of 8
[2022-12-07T16:44:00.863+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-07T16:44:00.878+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-12-07 16:07:12.235594+00:00
[2022-12-07T16:44:00.881+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 462 to run task
[2022-12-07T16:44:00.887+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'manual__2022-12-07T16:07:12.235594+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmpr58rt3uh']
[2022-12-07T16:44:00.889+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 31: Subtask get_raw_data_from_postgres_sources
[2022-12-07T16:44:00.941+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-07T16:07:12.235594+00:00 [running]> on host db3df0a6f633
[2022-12-07T16:44:00.994+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T16:07:12.235594+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T16:07:12.235594+00:00
[2022-12-07T16:44:01.007+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start getting data from source Postgres - Table: users
[2022-12-07T16:44:01.009+0000] {logging_mixin.py:137} INFO - ðŸ¤ª <db_handler.postgres_handler.PostgresHandler object at 0x7f3a9c419b80> SELECT user_id, name, email, mobile FROM public.users user_id, name, email, mobile
[2022-12-07T16:44:01.016+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_psql_source.py", line 57, in ingest_psql_source
    data = extract_data_from_source(postgres_handler=postgres_handler,
  File "/airflow/dags/processing/ingest_psql_source.py", line 12, in extract_data_from_source
    df = pd.DataFrame(data, columns=list_columns)
  File "/opt/bitnami/python/lib/python3.8/site-packages/pandas/core/frame.py", line 744, in __init__
    columns = ensure_index(columns)
  File "/opt/bitnami/python/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 7376, in ensure_index
    return Index._with_infer(index_like, copy=copy)
  File "/opt/bitnami/python/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 717, in _with_infer
    result = cls(*args, **kwargs)
  File "/opt/bitnami/python/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 546, in __new__
    raise cls._scalar_data_error(data)
TypeError: Index(...) must be called with a collection of some kind, 'user_id, name, email, mobile' was passed
[2022-12-07T16:44:01.027+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221207T160712, start_date=20221207T164400, end_date=20221207T164401
[2022-12-07T16:44:01.042+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 31 for task get_raw_data_from_postgres_sources (Index(...) must be called with a collection of some kind, 'user_id, name, email, mobile' was passed; 462)
[2022-12-07T16:44:01.060+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-07T16:44:01.074+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
