[2022-12-05T07:24:23.206+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources scheduled__2022-12-03T19:00:00+00:00 [queued]>
[2022-12-05T07:24:23.215+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources scheduled__2022-12-03T19:00:00+00:00 [queued]>
[2022-12-05T07:24:23.216+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:24:23.217+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-12-05T07:24:23.217+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:24:23.231+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_mysql_sources> on 2022-12-03 19:00:00+00:00
[2022-12-05T07:24:23.236+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 659 to run task
[2022-12-05T07:24:23.240+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_mysql_sources', 'scheduled__2022-12-03T19:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmp9avt2oaf']
[2022-12-05T07:24:23.241+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 2: Subtask get_raw_data_from_mysql_sources
[2022-12-05T07:24:23.296+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources scheduled__2022-12-03T19:00:00+00:00 [running]> on host 2387a8df1781
[2022-12-05T07:24:23.350+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_mysql_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T19:00:00+00:00
[2022-12-05T07:24:23.352+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:24:23.582+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:24:23.596+0000] {logging_mixin.py:137} INFO - ðŸ¤ª the dataframe is inserted
[2022-12-05T07:24:23.597+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:24:23.605+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:24:23.610+0000] {logging_mixin.py:137} INFO - ðŸ¤ª the dataframe is inserted
[2022-12-05T07:24:23.611+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:24:23.618+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:24:23.625+0000] {logging_mixin.py:137} INFO - ðŸ¤ª the dataframe is inserted
[2022-12-05T07:24:23.627+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:24:23.631+0000] {logging_mixin.py:137} INFO - ðŸ¤ª (1142, "SELECT command denied to user 'report_admin'@'172.18.0.2' for table 'menus'")
[2022-12-05T07:24:23.633+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:24:23.637+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/controller/get_raw_data_from_mysql_source.py", line 36, in get_raw_data_from_mysql_source
    execute_values(conn, data, table)
  File "/airflow/dags/controller/source_controller.py", line 8, in execute_values
    tuples = [tuple(x) for x in df.to_numpy()]
AttributeError: 'NoneType' object has no attribute 'to_numpy'
[2022-12-05T07:24:23.661+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_mysql_sources, execution_date=20221203T190000, start_date=20221205T072423, end_date=20221205T072423
[2022-12-05T07:24:23.675+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 2 for task get_raw_data_from_mysql_sources ('NoneType' object has no attribute 'to_numpy'; 659)
[2022-12-05T07:24:23.695+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-05T07:24:23.711+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
[2022-12-05T09:25:35.482+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources scheduled__2022-12-03T19:00:00+00:00 [queued]>
[2022-12-05T09:25:35.492+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources scheduled__2022-12-03T19:00:00+00:00 [queued]>
[2022-12-05T09:25:35.493+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T09:25:35.493+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-12-05T09:25:35.494+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T09:25:35.507+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_mysql_sources> on 2022-12-03 19:00:00+00:00
[2022-12-05T09:25:35.510+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 101 to run task
[2022-12-05T09:25:35.515+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_mysql_sources', 'scheduled__2022-12-03T19:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmpjb1d9j2p']
[2022-12-05T09:25:35.517+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 3: Subtask get_raw_data_from_mysql_sources
[2022-12-05T09:25:35.566+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources scheduled__2022-12-03T19:00:00+00:00 [running]> on host 97416e2a1062
[2022-12-05T09:25:35.618+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_mysql_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T19:00:00+00:00
[2022-12-05T09:25:35.765+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start getting data from source Mysql - Table: users
[2022-12-05T09:25:35.775+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Found 0 records need to be inserted
[2022-12-05T09:25:35.781+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start ingesting data from source Mysql to DW - Table: users
[2022-12-05T09:25:35.783+0000] {logging_mixin.py:137} INFO - ðŸ¤ª the dataframe is inserted
[2022-12-05T09:25:35.783+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Finished ingesting data from source to DW - Table: users
[2022-12-05T09:25:35.784+0000] {python.py:177} INFO - ðŸ¤ª Done. Returned value was: None
[2022-12-05T09:25:35.790+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as SUCCESS. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_mysql_sources, execution_date=20221203T190000, start_date=20221205T092535, end_date=20221205T092535
[2022-12-05T09:25:35.809+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 0
[2022-12-05T09:25:35.824+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
