[2022-12-05T07:33:35.380+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-12-05T07:24:23.686370+00:00 [queued]>
[2022-12-05T07:33:35.388+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-12-05T07:24:23.686370+00:00 [queued]>
[2022-12-05T07:33:35.389+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:33:35.389+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-12-05T07:33:35.390+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:33:35.402+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_mysql_sources> on 2022-12-05 07:24:23.686370+00:00
[2022-12-05T07:33:35.406+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 743 to run task
[2022-12-05T07:33:35.410+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_mysql_sources', 'manual__2022-12-05T07:24:23.686370+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmpxrbygdv9']
[2022-12-05T07:33:35.411+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 10: Subtask get_raw_data_from_mysql_sources
[2022-12-05T07:33:35.457+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-12-05T07:24:23.686370+00:00 [running]> on host 2387a8df1781
[2022-12-05T07:33:35.512+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_mysql_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T07:24:23.686370+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-05T07:24:23.686370+00:00
[2022-12-05T07:33:35.515+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:33:35.526+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:33:35.533+0000] {logging_mixin.py:137} INFO - ðŸ¤ª the dataframe is inserted
[2022-12-05T07:33:35.534+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:33:35.541+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:33:35.547+0000] {logging_mixin.py:137} INFO - ðŸ¤ª the dataframe is inserted
[2022-12-05T07:33:35.548+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:33:35.556+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:33:35.562+0000] {logging_mixin.py:137} INFO - ðŸ¤ª the dataframe is inserted
[2022-12-05T07:33:35.563+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Connecting to the MySQL database...
[2022-12-05T07:33:35.569+0000] {logging_mixin.py:137} INFO - ðŸ¤ª (1142, "SELECT command denied to user 'report_admin'@'172.18.0.2' for table 'menus'")
[2022-12-05T07:33:35.570+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Database connection closed.
[2022-12-05T07:33:35.576+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/controller/get_raw_data_from_mysql_source.py", line 36, in get_raw_data_from_mysql_source
    execute_values(conn, data, table)
  File "/airflow/dags/controller/source_controller.py", line 8, in execute_values
    tuples = [tuple(x) for x in df.to_numpy()]
AttributeError: 'NoneType' object has no attribute 'to_numpy'
[2022-12-05T07:33:35.585+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_mysql_sources, execution_date=20221205T072423, start_date=20221205T073335, end_date=20221205T073335
[2022-12-05T07:33:35.599+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 10 for task get_raw_data_from_mysql_sources ('NoneType' object has no attribute 'to_numpy'; 743)
[2022-12-05T07:33:35.622+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-05T07:33:35.637+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
