[2022-11-30T05:45:59.762+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-11-30T05:01:02.134850+00:00 [queued]>
[2022-11-30T05:45:59.798+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-11-30T05:01:02.134850+00:00 [queued]>
[2022-11-30T05:45:59.800+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T05:45:59.802+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 4 of 4
[2022-11-30T05:45:59.803+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T05:45:59.845+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_mysql_sources> on 2022-11-30 05:01:02.134850+00:00
[2022-11-30T05:45:59.850+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 722 to run task
[2022-11-30T05:45:59.854+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_mysql_sources', 'manual__2022-11-30T05:01:02.134850+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/get_data_from_sources.py', '--cfg-path', '/tmp/tmpzdhbvvim']
[2022-11-30T05:45:59.856+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 53: Subtask get_raw_data_from_mysql_sources
[2022-11-30T05:45:59.905+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-11-30T05:01:02.134850+00:00 [running]> on host 298e6b8d1257
[2022-11-30T05:45:59.950+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_mysql_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T05:01:02.134850+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T05:01:02.134850+00:00
[2022-11-30T05:45:59.953+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/pymysql/connections.py", line 613, in connect
    sock = socket.create_connection(
  File "/opt/bitnami/python/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/bitnami/python/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/controller/get_raw_data_from_mysql_source.py", line 8, in get_raw_data_from_mysql_source
    conn = pymysql.connect(host='localhost',
  File "/opt/bitnami/python/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/opt/bitnami/python/lib/python3.8/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")
[2022-11-30T05:45:59.958+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as FAILED. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_mysql_sources, execution_date=20221130T050102, start_date=20221130T054559, end_date=20221130T054559
[2022-11-30T05:45:59.968+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 53 for task get_raw_data_from_mysql_sources ((2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)"); 722)
[2022-11-30T05:45:59.987+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-11-30T05:46:00.000+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
