[2022-11-30T04:12:20.421+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T04:06:06.271989+00:00 [queued]>
[2022-11-30T04:12:20.429+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T04:06:06.271989+00:00 [queued]>
[2022-11-30T04:12:20.430+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T04:12:20.431+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 3 of 4
[2022-11-30T04:12:20.431+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T04:12:20.445+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-11-30 04:06:06.271989+00:00
[2022-11-30T04:12:20.449+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 289 to run task
[2022-11-30T04:12:20.453+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'manual__2022-11-30T04:06:06.271989+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/get_data_from_sources.py', '--cfg-path', '/tmp/tmpqkgix2ag']
[2022-11-30T04:12:20.455+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 23: Subtask get_raw_data_from_postgres_sources
[2022-11-30T04:12:20.500+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T04:06:06.271989+00:00 [running]> on host 298e6b8d1257
[2022-11-30T04:12:20.546+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T04:06:06.271989+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T04:06:06.271989+00:00
[2022-11-30T04:12:20.548+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/controller/get_raw_data_from_postgres_source.py", line 8, in get_raw_data_from_postgres_source
    conn = psycopg2.connect(
  File "/opt/bitnami/python/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2022-11-30T04:12:20.554+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221130T040606, start_date=20221130T041220, end_date=20221130T041220
[2022-11-30T04:12:20.564+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 23 for task get_raw_data_from_postgres_sources (connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 289)
[2022-11-30T04:12:20.585+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-11-30T04:12:20.599+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
