[2022-11-30T04:20:47.468+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T04:20:42.887840+00:00 [queued]>
[2022-11-30T04:20:47.475+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T04:20:42.887840+00:00 [queued]>
[2022-11-30T04:20:47.476+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T04:20:47.476+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-11-30T04:20:47.477+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T04:20:47.491+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-11-30 04:20:42.887840+00:00
[2022-11-30T04:20:47.497+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 347 to run task
[2022-11-30T04:20:47.502+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'manual__2022-11-30T04:20:42.887840+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/get_data_from_sources.py', '--cfg-path', '/tmp/tmpuxwuu7qh']
[2022-11-30T04:20:47.504+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 27: Subtask get_raw_data_from_postgres_sources
[2022-11-30T04:20:47.550+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T04:20:42.887840+00:00 [running]> on host 298e6b8d1257
[2022-11-30T04:20:47.606+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T04:20:42.887840+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T04:20:42.887840+00:00
[2022-11-30T04:20:47.608+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/controller/get_raw_data_from_postgres_source.py", line 8, in get_raw_data_from_postgres_source
    conn = psycopg2.connect(
  File "/opt/bitnami/python/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "0.0.0.0", port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2022-11-30T04:20:47.615+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221130T042042, start_date=20221130T042047, end_date=20221130T042047
[2022-11-30T04:20:47.624+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 27 for task get_raw_data_from_postgres_sources (connection to server at "0.0.0.0", port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 347)
[2022-11-30T04:20:47.635+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-11-30T04:20:47.648+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
