[2022-11-30T05:46:13.185+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T05:03:14.223869+00:00 [queued]>
[2022-11-30T05:46:13.199+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T05:03:14.223869+00:00 [queued]>
[2022-11-30T05:46:13.201+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T05:46:13.202+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-11-30T05:46:13.202+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T05:46:13.237+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-11-30 05:03:14.223869+00:00
[2022-11-30T05:46:13.251+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 735 to run task
[2022-11-30T05:46:13.265+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'manual__2022-11-30T05:03:14.223869+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/get_data_from_sources.py', '--cfg-path', '/tmp/tmp67dfznpd']
[2022-11-30T05:46:13.271+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 55: Subtask get_raw_data_from_postgres_sources
[2022-11-30T05:46:13.435+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-11-30T05:03:14.223869+00:00 [running]> on host 298e6b8d1257
[2022-11-30T05:46:13.666+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T05:03:14.223869+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T05:03:14.223869+00:00
[2022-11-30T05:46:13.691+0000] {logging_mixin.py:137} INFO - ðŸ¤ª connect succeeded
[2022-11-30T05:46:13.787+0000] {logging_mixin.py:137} INFO - ðŸ¤ª data:       id        name  ...                 created_at updated_at
0     1      Rivera  ... 2022-11-30 03:46:58.296313       None
1     2    Phillips  ... 2022-11-30 03:46:58.296313       None
2     3        Ross  ... 2022-11-30 03:46:58.296313       None
3     4       Lewis  ... 2022-11-30 03:46:58.296313       None
4     5      Walker  ... 2022-11-30 03:46:58.296313       None
..  ...         ...  ...                        ...        ...
95   96    Phillips  ... 2022-11-30 03:46:58.296313       None
96   97       Green  ... 2022-11-30 03:46:58.296313       None
97   98  Washington  ... 2022-11-30 03:46:58.296313       None
98   99  Washington  ... 2022-11-30 03:46:58.296313       None
99  100      Cooper  ... 2022-11-30 03:46:58.296313       None

[100 rows x 6 columns]
[2022-11-30T05:46:13.830+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Error: duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
[2022-11-30T05:46:13.834+0000] {python.py:177} INFO - ðŸ¤ª Done. Returned value was: None
[2022-11-30T05:46:14.025+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as SUCCESS. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221130T050314, start_date=20221130T054613, end_date=20221130T054614
[2022-11-30T05:46:14.089+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 0
[2022-11-30T05:46:14.152+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
